## NumPy

NumPy to podstawowy pakiet do obliczeń naukowych w Pythonie. Zawiera między innymi:
- wydajny n-wymiarowy obiekt tablicy
- zaawansowane funkcje (nadawanie)
- narzędzia do integracji z C/C ++ i Fortran
- operacje algebry liniowej, transformatę Fouriera i generator liczb losowych

In [1]:
import numpy as np

### Tablica

Podstawowym obiektem w NumPy jest tablica `ndarray`. Talbicę można stworzyć z kolekcji za pomocą funkcji `ndarray` lub jej aliasu `array`.

In [2]:
n1 = np.array([1,2,3])
print(n1)
n2 = np.array([[1,2],[3,4]])
n2

[1 2 3]


array([[1, 2],
       [3, 4]])

In [3]:
print('Wymiar: n1: {}, n2: {}'.format(n1.ndim, n2.ndim))
print('Kształt: n1: {}, n2: {}'.format(n1.shape, n2.shape))
print('Rozmiar: n1: {}, n2: {}'.format(n1.size, n2.size))
print('Typ: n1: {}, n2: {}'.format(n1.dtype, n2.dtype))
print('Rozmiar elementu (w bajtach): n1: {}, n2: {}'.format(n1.itemsize, n2.itemsize))
print('Wskaźnik do danych: n1: {}, n2: {}'.format(n1.data, n2.data))

Wymiar: n1: 1, n2: 2
Kształt: n1: (3,), n2: (2, 2)
Rozmiar: n1: 3, n2: 4
Typ: n1: int64, n2: int64
Rozmiar elementu (w bajtach): n1: 8, n2: 8
Wskaźnik do danych: n1: <memory at 0x7f346aec3108>, n2: <memory at 0x7f346b265cf0>


W przeciwieństwie do kolekcji, tablice mogą mieć tylko jeden typ elementu.

In [4]:
for v in [1, 1., 1j]:
    a = np.array([v])
    print('Tablica: {}, typ: {}'.format(a, a.dtype))
# można wymusić typ przy tworzeniu tablicy
a = np.array([1], dtype=str)
print('Tablica: {}, typ: {}'.format(a, a.dtype))

Tablica: [1], typ: int64
Tablica: [ 1.], typ: float64
Tablica: [ 0.+1.j], typ: complex128
Tablica: ['1'], typ: <U1


Ogólne metody tworzenia tablic o specyficznych właściwościach.

In [50]:
print('Zakres:\n{}'.format(np.arange(1,10)))
print('Zera:\n{}'.format(np.zeros((2,3))))
print('Jedynki:\n{}'.format(np.ones((3,2))))
print('Pusta:\n{}'.format(np.empty((2,7)))) # bez inicjalizacji
print('Losowa:\n{}'.format(np.random.rand(2,2)))

Zakres:
[1 2 3 4 5 6 7 8 9]
Zera:
[[ 0.  0.  0.]
 [ 0.  0.  0.]]
Jedynki:
[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]
Pusta:
[[  6.91019061e-310   1.71232560e-316   0.00000000e+000   0.00000000e+000
    0.00000000e+000   0.00000000e+000   0.00000000e+000]
 [  0.00000000e+000   0.00000000e+000   0.00000000e+000   0.00000000e+000
    0.00000000e+000   0.00000000e+000   0.00000000e+000]]
Losowa:
[[ 0.54927261  0.99479974]
 [ 0.85014886  0.57351572]]


Pobieranie wartości z tablic.

In [6]:
print(n1)
print(n2)
# jak w kolekcjach
print(n1[1], n2[1][1])
# lub krócej
print(n2[1,1])
# przecięcia podobnie w kolekcjach
print(n2[1,:])
print(n2[:,1])
print(n2[1,:1])

[1 2 3]
[[1 2]
 [3 4]]
2 4
4
[3 4]
[2 4]
[3]


Operacje w tablicach wykonywane są na poszczególnych elementach, np. jak pomnożymy dwie tablice pomnożone zostaną tylko elementy na tych samych pozycjach przez siebie.

In [51]:
a = np.random.randint(10,size=(2,3))
print('a = \n{}'.format(a))
print('2*a = \n{}'.format(2*a))
print('a**2 = \n{}'.format(a**2))
print('a*a = \n{}'.format(a*a))

a = 
[[3 6 9]
 [1 4 1]]
2*a = 
[[ 6 12 18]
 [ 2  8  2]]
a**2 = 
[[ 9 36 81]
 [ 1 16  1]]
a*a = 
[[ 9 36 81]
 [ 1 16  1]]


### Macierze

Numpy ma również typ macierzy `matrix`. Jest on podobny do tablicy ale podstawowe operacje wykonywane są w sposób macierzowy a nie tablicowy.

In [52]:
m = np.matrix([[1,2], [3,4]])
mm = np.matrix([[5,6], [7,8]])

print('m*mm = \n{}'.format(m*mm))
print('m**2 = \n {}'.format(m**2))
print('m*2 = \n ={}'.format(m*2))

d = np.diag([3,4])
print('d = \n {}'.format(d))
print('d*m = \n {}'.format(d*m))

m*mm = 
[[19 22]
 [43 50]]
m**2 = 
 [[ 7 10]
 [15 22]]
m*2 = 
 =[[2 4]
 [6 8]]
d = 
 [[3 0]
 [0 4]]
d*m = 
 [[ 3  6]
 [12 16]]


Tablic można używać podobnie wykorzystując odpowiednie funkcje (np. `dot`).

In [53]:
a = np.array([[1,2], [3,4]])
aa = np.array([[5,6], [7,8]])

print('a*aa = \n{}'.format(a*aa))
print('a.dot(aa) = \n{}'.format(a.dot(aa)))
print('a**2 = \n {}'.format(a**2))
print('a*2 = \n ={}'.format(a*2))

a*aa = 
[[ 5 12]
 [21 32]]
a.dot(aa) = 
[[19 22]
 [43 50]]
a**2 = 
 [[ 1  4]
 [ 9 16]]
a*2 = 
 =[[2 4]
 [6 8]]


Operacje algebry liniowej można wykonywać zarówno na tablicach jak i macierzach

In [54]:
print('det(m) = {}'.format(np.linalg.det(m)))
print('det(a) = {}'.format(np.linalg.det(a)))

det(m) = -2.0000000000000004
det(a) = -2.0000000000000004


## Zadanie
Mamy liczbę trzycyfrową. Jeżeli od liczby dziesiątek odejmiemy liczbę jedności otrzymamy 6. Jeżeli do liczby dziesiątek dodamy liczbę jedności otrzymamy 10.

* znajdź wszystkie liczby trzycyfrowe spełniające ten warunek
* znajdź liczby trzycyfrowe podzielne przez 3

[Podpowiedź](https://pl.wikipedia.org/wiki/Uk%C5%82ad_r%C3%B3wna%C5%84_liniowych):
$$ Ax=B $$
$$ x = A^{-1}B $$

In [61]:
a = np.array([[1,-1], [1,1]])
b = np.array([[6], [10]])

print('a = \n{}'.format(a))
print('b = \n{}'.format(b))

print('a.dot(b) = \n{}'.format(a.dot(b)))


a = 
[[ 1 -1]
 [ 1  1]]
b = 
[[ 6]
 [10]]
a.dot(b) = 
[[-4]
 [16]]


In [101]:
A = np.matrix([[1, -1], [1, 1]])

In [107]:
B = np.array([[6], [10]])

In [108]:
C = np.linalg.inv(A)
C

matrix([[ 0.5,  0.5],
        [-0.5,  0.5]])

In [112]:
x = np.dot(C,B)
x

matrix([[ 8.],
        [ 2.]])

In [110]:
C.dot(B)

matrix([[ 8.],
        [ 2.]])

In [92]:
w = np.arange(1,10)
w

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
w = w *100
w

array([100, 200, 300, 400, 500, 600, 700, 800, 900])

In [83]:
w = w+ 80 + 2
w

array([182, 282, 382, 482, 582, 682, 782, 882, 982])

In [88]:
w[w % 3 == 0]

array([282, 582, 882])